import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import colors from '@utils/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.themebg,
  },
  parentContainer: {
    flex: 1,
    backgroundColor: colors.themebg,
    padding: wp(5),
    borderRadius: wp(4),
  },
  parentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignSelf: 'flex-start',
  },
  listImg: {
    borderRadius: wp(2),
    resizeMode: 'cover',
  },

  deviderView: {
    width: '100%',
    height: 0.5,
    backgroundColor: colors.borderGray,
  },
  textView: {
    width: '60%',
    height: hp(0.3),
    backgroundColor: colors.blue100,
    marginBottom: hp(2),
  },
  tagLabel: {
    fontSize: wp(4.5),
    color: colors.white,
    alignSelf: 'center',
    marginHorizontal: wp(4),
    maxWidth: wp(50),
    lineHeight: hp(3),
    fontFamily: 'Inter-Bold',
  },
  descLabel: {
    fontSize: wp(4),
    color: colors.white,
    lineHeight: hp(3),
    fontFamily: 'Inter-Regular',
  },
  movieTitle: {
    maxWidth: wp(50),
    fontSize: wp(5),
    fontWeight: 'bold',
  },
  showingParent: {
    marginRight: wp(5),
  },
  headerView: {
    backgroundColor: colors.navy10,
    justifyContent: 'space-around',
    borderBottomColor: 'transparent',
    // position: 'absolute',
    // top: hp(1),
    // zIndex: 1,
    height: hp(15),
    paddingHorizontal: wp(6),
  },
  logoImg: {
    width: wp(10),
    height: wp(10),
    // alignSelf: 'center',
    resizeMode: 'contain',
  },
  notiImg: {
    width: wp(8),
    height: wp(8),
    resizeMode: 'contain',
  },
  genreView: {
    borderRadius: wp(5),
    width: wp('20%'),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: wp(2),
    backgroundColor: '#F2F4F7',
    height: hp(4),
  },
  genreTxt: {
    color: '#11468F',
    maxWidth: wp('18%'),
  },
  listParent: {
    flexGrow: 1,
    marginVertical: hp(3),
  },
  childContainer: {
    margin: wp(4),
  },
  renderView: {
    width: wp(40),
    height: wp(40),
    backgroundColor: 'green',
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: wp(5),
    marginTop: hp(3),
    marginHorizontal: wp(2),
  },
  listParentContainer: {
    flexGrow: 1,
    alignItems: 'center',
    width: '100%',
    justifyContent: 'space-between',
  },
  colStyle: {
    justifyContent: 'center',
  },
  listPieContainer: {
    flexGrow: 1,
    width: '100%',
    justifyContent: 'space-between',
  },
  listYearContainer: {
    flexGrow: 1,
    width: '100%',
    justifyContent: 'space-between',
    paddingHorizontal: wp(5),
  },
  innerView: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 0,
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  amcTitle: {
    fontSize: wp(4),
    color: colors.white,
    alignSelf: 'center',
    marginHorizontal: wp(4),
    maxWidth: wp(50),
    lineHeight: hp(3),
    fontFamily: 'Inter-SemiBold',
  },
  amcNumber: {
    fontSize: wp(3.5),
  },
  amcIcon: {
    fontSize: wp(8),
    color: colors.white,
    marginVertical: wp(1),
  },
  stockIcon: {
    fontSize: wp(6),
    color: colors.lightBlue,
    marginVertical: wp(1),
  },
  backIcon: {
    fontSize: wp(5),
    color: colors.white,
    marginVertical: wp(1),
  },
  schemeLabel: {
    fontSize: wp(5),
    color: colors.white,
    lineHeight: hp(3),
    textAlign: 'center',
    marginVertical: hp(2),
    fontFamily: 'Inter-Bold',
  },
  schemeView: {
    backgroundColor: colors.neutral800,
    borderTopLeftRadius: wp(5),
    borderTopRightRadius: wp(5),
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
  },
  schemeBg: {
    backgroundColor: 'transparent',
  },
  schemeLabelName: {
    fontSize: wp(4.3),
    color: colors.white,
    lineHeight: hp(3),
    textAlign: 'center',
    marginVertical: hp(2),
    fontFamily: 'Inter-Bold',
  },
  childScheme: {
    width: '100%',
  },
  childLabelName: {
    fontSize: wp(4.3),
    color: colors.secondary100,
    lineHeight: hp(3),
    textAlign: 'center',
    marginVertical: hp(2),
    fontFamily: 'Inter-Regular',
  },
  listSchemeContainer: {
    flexGrow: 1,
    width: '100%',
    justifyContent: 'space-between',
    borderRadius: wp(5),
    borderWidth: wp(0.1),
    borderColor: colors.borderGray,
  },
  objLabel: {
    fontSize: wp(5),
    color: colors.white,
    lineHeight: hp(3),
    fontWeight: 'bold',
    marginTop: hp(2),
  },
  pieView: {
    marginHorizontal: wp(4),
    marginTop: hp(3),
    alignItems: 'center',
  },
  yearView: {
    alignItems: 'center',
    height: wp(7),
    justifyContent: 'center',
    paddingHorizontal: wp(1),
    marginTop: hp(1),
  },
  yearContainer: {
    borderRadius: wp(5),
    borderWidth: wp(0.1),
    borderColor: colors.secondary300,
    backgroundColor: colors.neautral700,
    width: wp(15),
    borderBottomColor: colors.blue100,
  },
  yearTitle: {
    color: colors.white,
    fontSize: wp(3),
  },
  yearBold: {
    fontFamily: 'Inter-Bold',
  },
  pieTitle: {
    color: colors.white,
    marginVertical: hp(2),
    fontSize: wp(4.5),
    fontFamily: 'Inter-SemiBold',
  },
  pieInner: {
    backgroundColor: 'transparent',
    position: 'absolute',
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  stockLabel: {
    fontSize: wp(4),
    color: colors.white,
    lineHeight: hp(3),
    fontFamily: 'Inter-Bold',
  },
  stockView: {
    flexDirection: 'row',
    backgroundColor: colors.neautral700,
    width: '30%',
    borderRadius: wp(5),
    justifyContent: 'space-evenly',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: hp(2),
    marginBottom: hp(1),
  },
  graphView: {
    backgroundColor: colors.black,
    borderRadius: wp(2),
    borderWidth: wp(0.1),
    borderColor: 'gray',
    height: hp(40),
    justifyContent: 'center',
    marginTop: hp(3),
  },
  chartView: {
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    paddingRight: 0,
    backgroundColor: 'transparent',
  },
  barView: {
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: wp(5),
    paddingRight: 0,
    backgroundColor: 'transparent',
  },
});
